### ISSUE TITLE
BOW EOW problem

### ISSUE THREAD

**Issue by dwaydwaydway** [bamtercelboo/cw2vec#14]
I don't think they add '<' and '>' to each word in the paper(substroke model)
![image](https://user-images.githubusercontent.com/33707393/58744065-876fd400-846f-11e9-8033-523a09feb871.png)

**Comment by dalinvip** [comment]
Yes, it's not mentioned in the paper, this is a detail, not quite sure how the source code is implemented. 
For Chinese character "一", the stoke is "一", maybe should add "<" and ">" for 3-ngrams.
The code is implemented by referring to fasttext.
Thanks.
