### ISSUE TITLE
你好，大量数据训练时出现问题，请问能否帮忙看一下

### ISSUE THREAD

**Issue by tantingting1012** [bamtercelboo/cw2vec#15]
数据集1.4G，使用提供的字符信息训练时cw2vec模型出现问题如下
Train Embedding By Using [substoke] model
terminate called after throwing an instance of 'std::invalid_argument'
  what():  merge.seg.txtcannot be opened for training!
Aborted (core dumped)

**Comment by dalinvip** [comment]
merge.seg.txt 路径写的对吗

**Comment by tantingting1012** [comment]
没问题的

**Comment by dalinvip** [comment]
那就肉眼看不出来是什么问题了

**Comment by tantingting1012** [comment]
你好，现在变成了这种问题，请问您能帮忙看一下嘛
Train Embedding By Using [substoke] model
Training From ./sample/merge.seg.txt
Read 154M words(705845) 
featuremap size	20901
initail feature, maybe take a while...... 
initail feature finished. 
initail Ngrams feature, maybe take a while...... 
initail Ngrams feature finished. 
Read 154M words
Number of all words:  154449042
Number of all words:  7725147
Number of words:  705845
Number of features: 24271665
Number of targets: 705845
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by tantingting1012** [comment]
我把词向量维度改成了300维，不知道是不是这个原因呢

**Comment by dalinvip** [comment]
仅仅更改向量维度是不会出现这个问题的。
训练cw2vec的时候要注意笔画文件是否正确

**Comment by tantingting1012** [comment]
emmm，我使用的是您提供的stoke文件

**Comment by dalinvip** [comment]
这就很奇怪了，我好久没训练这个模型了。不过都是没问题的，你训练其他的模型有问题吗

**Comment by tantingting1012** [comment]
你好，其他训练也是这个错误
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
terminate called recursively
  Aborted (core dumped)

**Comment by tantingting1012** [comment]
你好，这个问题我解决了，感谢您

**Comment by dalinvip** [comment]
具体是什么原因呢，环境的问题嘛？

**Comment by tantingting1012** [comment]
数据的问题，我所有的数据是一行，后面分行了就可以啦

**Comment by tantingting1012** [comment]
您好，方便问一下你这个项目对中文分词在哪个文件里面做的吗

**Comment by tantingting1012** [comment]
或者您这边使用的什么分词工具呢，是否可以支持自定义词典，我做的是领域十分密切相关的任务，想通过自定义词典监督分词不知道是否可行

**Comment by dalinvip** [comment]
jieba + user_dict

**Comment by tantingting1012** [comment]
哦哦，这边分词部分代码是打包过的，无法支持我这边自己添加词典的做法，对吗，

**Comment by dalinvip** [comment]
cw2vec、word2vec是在你分词的基础之上训练embedding，至于怎么分词，什么方法，可以自定
