### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by yuanjie-ai** [bamtercelboo/cw2vec#2]
In file included from /algor/zhouc/cw2vec/word2vec/src/main.cpp:13:0:
/algor/zhouc/cw2vec/word2vec/src/include/args.h: In member function ‘void Args::parseArgs(const std::vector<std::basic_string<char> >&)’:
/algor/zhouc/cw2vec/word2vec/src/include/args.h:168:10: error: expected type-specifier
   catch (std::out_of_range){
          ^
/algor/zhouc/cw2vec/word2vec/src/include/args.h:168:27: error: expected unqualified-id before ‘)’ token
   catch (std::out_of_range){
                           ^
make[2]: *** [src/CMakeFiles/word2vec.dir/main.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/word2vec.dir/all] Error 2
make: *** [all] Error 2

**Comment by dalinvip** [comment]
clone this code and run it,  I didn't see the problem, how did this happen?

**Comment by dalinvip** [comment]
please make sure that gcc version >= 5.4.0
