### ISSUE TITLE
、、、

### ISSUE THREAD

**Issue by z744364418p** [bamtercelboo/cw2vec#4]
运行run.sh 没反应

**Comment by dalinvip** [comment]
./word2vec skipgram -input train.txt(你的训练文件) -output skipgram_out（输出文件名） -lr 0.025 -dim 100 -ws 5 -epoch 5 -minCount 10 -neg 5 -loss ns -thread 8 -t 1e-4 -lrUpdateRate 100 

这个是运行skipgram的，其余的类似，前提先根据readme用cmake,make编译之后，在bin文件夹下会生成可执行文件，在bin目录下运行上述命令。

**Comment by dalinvip** [comment]
现在你可以直接运行run.sh试一下
