### ISSUE TITLE
由和田训练出来的向量会是一样的么？

### ISSUE THREAD

**Issue by CrazyTianC** [bamtercelboo/cw2vec#6]
如题

**Comment by dalinvip** [comment]
不好意思，没明白你是什么意思

**Comment by CrazyTianC** [comment]
就是有一些笔画相同的但是字形不同的字，比如由和田。我看论文里是没有提这个，那他们的n-gram是相同的，最后这两个字的向量也会相同。我这么理解是不是哪里不太对。。。

**Comment by dawnranger** [comment]
有趣的问题，这篇论文应该还没有解决这个问题。

**Comment by dalinvip** [comment]
这种笔画一致或者相似的中文汉字有人有过统计嘛
