### ISSUE TITLE
cw2vec training process

### ISSUE THREAD

**Issue by OYE93** [bamtercelboo/cw2vec#7]
Hello, I have two questions:
1. how to deal with English letters and numbers in train or test samples?
2. this embedding is for words, does it suitable for character embeddings training?
Thanks!

**Comment by dalinvip** [comment]
1. all non-chinese characters can be cleaned out.
2. not only suitable for words but also for words, it is same as word2vec.

**Comment by OYE93** [comment]
Thanks for your kind reply. To my understanding, when training we can exclude all non Chinese characters, but when I use the trained embeddings in next step application, like NER, CLASSIFICATION, did you have any ideas in how to process the English letters and numbers in the encode process of rawtext.

**Comment by dalinvip** [comment]
If non-chinese characters are more, you can also save these non-chinese characters in the training data, they can be represented as different embedding same as word2vec, but it might have a little bit of an impact on training.

**Comment by OYE93** [comment]
老哥，我用中文问了哈。。。
是说在训练cw2vec embedding的时候也可以把英文字母和数字加进去训练吗，还是说在cw2vec embedding训练的时候不要把字母和数字加进去训练，但是在句子encode的时候用word2vec训练的字母和数字的embedding来表示，进行NER或者classification训练

**Comment by dalinvip** [comment]
我写的这份代码，我刚才又确认了一下，cw2vec训练的时候可以把非中文字符加进去训练，最终不同的非中文字符得到的结果会是不同的embedding来表示的，这样在NER，classification任务中，对于非中文字符就可以直接使用cw2vec训练出来的embedding来表示。

**Comment by HITxuefeng** [comment]
你好，我在进行make的时候报错，可以帮我看一下吗？
![image](https://user-images.githubusercontent.com/22385231/45399507-e50e8700-b67a-11e8-8793-252beec6db1e.png)

**Comment by dalinvip** [comment]
@HITxuefeng 我在编译的时候是没有问题的，应该是版本的问题

**Comment by HITxuefeng** [comment]
make的版本问题吗？

**Comment by dalinvip** [comment]
@HITxuefeng 看一下我的requment吧，看看那三个你是不是都满足

**Comment by OYE93** [comment]
@bamtercelboo 好的好的，感谢！
