### ISSUE TITLE
如何训练大规模语料

### ISSUE THREAD

**Issue by xiaocuigit** [bamtercelboo/cw2vec#8]
您好，之前使用您提供的代码实现了小规模的字向量的构建，但现在需要对百度百科这种规模的语料训练词向量，想使用笔画特征来训练，请问对于这种涉及到多个文件的语料该如何训练？还有，看您的代码里面好像没有提供GPU加速功能吧？

**Comment by dalinvip** [comment]
多个文件合并成一个文件，google的word2vec C语言版本的语料是什么格式，这份代码的的语料格式一样，另外，这个C++版本的速度不是很慢，笔画特征用的越多，可能会慢一些，采用多线程训练就可以，同时采用C或者C++版本用简单的sg或cbow，速度相差无几。c++版本没有GPU加速，没有使用pytorch或者dynet等深度学习库。

**Comment by xiaocuigit** [comment]
非常感谢能够回复。
