### ISSUE TITLE
Why not save the n-gram vectors?

### ISSUE THREAD

**Issue by semi-nothing** [bamtercelboo/cw2vec#9]
I have a question here. Why not save the n-gram vectors and so we can use it to solve OOV in some degree?

**Comment by semi-nothing** [comment]
Emmm. Another question. I modified your data and output the feature vector for cw2vec. I found that the word sometimes has "<" or ">" or both of them, I don't understand why the characters happen. Thank you so much in advance.

**Comment by dalinvip** [comment]
@semi-nothing 
Hi, Chinese characters "中“， it`s stoke information is "<丨フ一丨>"，"<" or ">" is the start and end flag in code.

**Comment by semi-nothing** [comment]
"<" represents the start of a word or "<" is just used to distinguish that "<丨フ" as the beginning of a sentence and "丨フ" as the middle part of a sentence?

And if it means as you said, how to cal average vectors of a word? If there is stoke "丨フ一丨" for "中", then we just use vector of "丨フ一丨" to represent "中", rather than n-gram features's vectors?

**Comment by dalinvip** [comment]
use "<丨フ一丨>" to calculate the average vectors of "中". you can see fasttext code for more information.

**Comment by semi-nothing** [comment]
Okay, thank you so much, I'll read it. Thank you!

bamtercelboo <notifications@github.com> 于2019年1月24日周四 下午7:12写道：

**Comment by dalinvip** [comment]
Thanks for your attention, too.
